### ISSUE TITLE
Load more than one YAML Corpus

### ISSUE THREAD

**Issue by diegodorgam** [RocketChat/hubot-natural#21]
Makes sense to load more than one YAML corpus?

Some people have asked about this, so they would be able to develop a YAML corpus specialized in some context area, our some specific subject in different files so it would be easier to develop, share and contribute.

What you think about it?

**Comment by MatheusFaria** [comment]
I think that would be interesting. The configuration could be through the `corpus` env variable, if you pass a folder you train with all YAML from it, if you pass a file you train from this single source.
