### ISSUE TITLE
good, when I try to start hubot tells me the following erorr:

### ISSUE THREAD

**Issue by orlando9006** [RocketChat/hubot-natural#29]
D:\documentos\mio\proyectoRobot\hubot-adry\bin>hubot
up to date in 0.704s
The system cannot find the path specified.I'm trying to use it on windows, could you help me

**Comment by diegodorgam** [comment]
Hi @orlando9006 ,

do you have anymore logs on this?

The file paths are not absolute, so you shouldn't have problems finding the training_data files inside of the folder on windows.

**Comment by orlando9006** [comment]
do you speak Spanish?

**Comment by diegodorgam** [comment]
sí,  per supuesto ;)

**Comment by orlando9006** [comment]
estoy tratando de crear mi propio chatbot, basado en su proyecto he seguido todos los pasos que me pones en la pagina, pero cuando voy a ejecutar a hubot me dice que el sisteme no puede encontrar la direccion especificada, existe algun archivo de configuracion donde deba cambiar algo?,es necesario crear alguna variable del entorno?, le agradeceria mucho si pudiese ayudarme.

**Comment by diegodorgam** [comment]
@orlando9006 sí, pero pienso que necessitas de suporte y no de una issue.
puede acender a el canal https://open.rocket.chat/channel/hubot-natural ?

**Comment by diegodorgam** [comment]
I'll be closing this for now
